#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'common_service'
require 'thrift_interface_types'

module CityWeatherInfoService
  class Client < ::CommonService::Client 
    include ::Thrift::Client

    def getCityWeatherInfo(commonRequest, cityInfo)
      send_getCityWeatherInfo(commonRequest, cityInfo)
      return recv_getCityWeatherInfo()
    end

    def send_getCityWeatherInfo(commonRequest, cityInfo)
      send_message('getCityWeatherInfo', GetCityWeatherInfo_args, :commonRequest => commonRequest, :cityInfo => cityInfo)
    end

    def recv_getCityWeatherInfo()
      result = receive_message(GetCityWeatherInfo_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'getCityWeatherInfo failed: unknown result')
    end

  end

  class Processor < ::CommonService::Processor 
    include ::Thrift::Processor

    def process_getCityWeatherInfo(seqid, iprot, oprot)
      args = read_args(iprot, GetCityWeatherInfo_args)
      result = GetCityWeatherInfo_result.new()
      result.success = @handler.getCityWeatherInfo(args.commonRequest, args.cityInfo)
      write_result(result, oprot, 'getCityWeatherInfo', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class GetCityWeatherInfo_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    COMMONREQUEST = 1
    CITYINFO = 2

    FIELDS = {
      COMMONREQUEST => {:type => ::Thrift::Types::STRUCT, :name => 'commonRequest', :class => ::CommonRequest},
      CITYINFO => {:type => ::Thrift::Types::STRUCT, :name => 'cityInfo', :class => ::CityWeatherInfoRequest}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class GetCityWeatherInfo_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRING, :name => 'success'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

