#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class CommonRequest
  include ::Thrift::Struct, ::Thrift::Struct_Union
  REQUESTER = 1
  REQUESTID = 2

  FIELDS = {
    REQUESTER => {:type => ::Thrift::Types::STRING, :name => 'requester'},
    REQUESTID => {:type => ::Thrift::Types::I32, :name => 'requestId'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class CityWeatherInfoRequest
  include ::Thrift::Struct, ::Thrift::Struct_Union
  CITYNAME = 1

  FIELDS = {
    CITYNAME => {:type => ::Thrift::Types::STRING, :name => 'cityName'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

